### ISSUE TITLE
Compilation issues when using different root directory

### ISSUE THREAD

**Issue by canelhasmateus** [sveltejs/vite-plugin-svelte#23] opened 2021-04-02 21:16 UTC
# Description

When using typescript and specifying a different root directory via vite.config.js , compilation issues arise .

## Reproduction

1 - In the provided zip, start the server, which behaves as expected. I'm running the command  ``` yarn run dev```

2 - Move the index.html inside another directory, changing the root directory inside vite.config.js accordingly -> At this point, the server starts up and displays only plain html, which is to be expected, since it couldn't find the script.

3 - Update the 'src' property inside the index to correctly point to the main.ts module. At this point, i'm getting a unexpected token exception. Its interesting to note that the server does starts, and the error occurs only when accessing the url.

## Additional Information

Initially, i thought it had something to do with the tsconfig.json properties or path, but after changing compilerOptions, and moving the file around ( specifying its path with the tsconfigFile property inside svelte.config.js , i could not reproduce the issue.

The vite-plugin ( not included in the zip ) was installed following the directives in this repo readme.md.

![error](https://user-images.githubusercontent.com/31675756/113454763-623bac00-93df-11eb-930d-68aa2dd25e32.png)
[envinfo.txt](https://github.com/sveltejs/vite-plugin-svelte/files/6251259/envinfo.txt)
[canelhasio.zip](https://github.com/sveltejs/vite-plugin-svelte/files/6251261/canelhasio.zip)

**Comment by dominikg** [comment] 2021-04-03 22:45
the issue is caused by the fact that vite-plugin-svelte currently reads svelte.config.cjs from vites root directory

https://github.com/sveltejs/vite-plugin-svelte/blob/0e516a39c50e23fc6fdc81dd4bee98b9a13c1331/packages/vite-plugin-svelte/src/utils/options.ts#L126

So for svelte to have the typescript preprocessor working  you'd have to move that config into src aswell or pass it inline in vite config. 
I also recommend you use the `svelte-ts` template from vites create app `npm init @vitejs/app`  as a base or take a look at sveltekit.  The regular svelte typesrcipt starter template is not a good base for vite projects.

Regarding svelte config location i'd love to get feedback what the best option would be for your usecase.

**Comment by canelhasmateus** [comment] 2021-04-04 05:42
This was a existing project that i tried migrating into vite, hence the ts template. About the use case, i'm not really sure if i'm the guy to listen too - i'm mainly a backend developer, and pretty new to this whole frontend world.

That being said: i dislike the way most frontend projects pollute the root directory. Mixing compiler configurations in the same directory as the initial page seems counter-intuitive to me.  

Vite configurations ( publicDir, outDir) seem to specify these directory in terms relative to the root. Maybe the plugin could follow,  taking root-relative path as configuration parameters?

Since most people seem to use default configurations without second thought, i'm not exactly sure  if such a change would be impactful for the "general population" Even so, it may be interesting to have in mind the public / demographic the project aims to cater to? Personally, i considered many frameworks before picking svelte, for it was: small, performant, concise, configurable.

**Comment by bhvngt** [comment] 2021-04-06 17:14
I am facing a similar regression. I recently upgraded my package from @svitejs/vite-plugin-svelte to this repo. Now when I run vite, I am getting following error while running vite. This use to work fine with @svitejs/vite-plugin-svelte 0.10.0. It broke with 0.11.1 and is giving the same issue when moved to this repo.

```
Uncaught SyntaxError: The requested module '/@fs/..../web/node_modules/.pnpm/svelte@3.37.0/node_modules/svelte/store/index.mjs?v=7d2ea93a' does not provide an export named 'Writable'
```

My vite.config.js is as follows

```
import {defineConfig} from "vite";
import svelte from "@sveltejs/vite-plugin-svelte";
import sveltePreprocess from "svelte-preprocess";

export default defineConfig(() => {
  return {
    root: "src",
    plugins: [svelte({
      preprocess: sveltePreprocess({
        postcss: true
      })
    })],
  };
});

```
I have not kept `svelte.config.js` inside src as I tried to inline them into vite.config.js

**Comment by dominikg** [comment] 2021-04-29 18:57
vite-plugin-svelte@1.0.0-next.8 added a new option `configFile`

either relative to vite root: `svelte({configFile:"../svelte.config.js"})` 
or absolute: `svelte({configFile:"/home/user/myglobalconfs/svelte.config.js"})`

Does that solve your problems when using "src" as vite root?

**Comment by dominikg** [comment] 2021-05-01 09:43
no, svelte.config.ts is not supported right now. 
It could be added but that would have to be a concerted effort as there are other tools also reading svelte config. 
You could setup your own transpile step to use it without framework support

**Comment by dominikg** [comment] 2021-05-02 21:03
closing here as the original issue can be solved with relative configFile option added in 1.0.0-next.8: `svelte({configFile:"../svelte.config.js"})`

**Closed by dominikg** 2021-05-02 21:03 UTC
Labels: bug, has-workaround
