### ISSUE TITLE
Ignores compilerOptions.generate

### ISSUE THREAD

**Issue by ghostdevv** [sveltejs/vite-plugin-svelte#345] opened 2022-05-24 20:22 UTC
### Describe the bug

@jakobrosenberg and I are trying to generate two builds of a vite app and we can't get v-p-s to always force ssr to false

Jake came up with the following workaround:
https://github.com/roxiness/routify.dev/commit/e8638a8ca48fd9cf503fdd60a608217853b27720#diff-58e6f63d87181b1c6a8cb6e5f1691df04aa32854456efcd52ca71c8541375d26R14

### Reproduction

We have these scripts in the package.json:

```json
{
    "build:client": "vite build --outDir dist/client",
    "build:server": "vite build --outDir dist/server --ssr src/main.js",
}
```

and trying to force ssr to always be false for svelte here:

```js
    svelte({
      compilerOptions: { generate: "dom", format: "esm" },
```

### Logs

```shell
https://gist.github.com/ghostdevv/0850dada3de50545b3b2e556f688afe4
```

### System Info

```shell
System:
    OS: Linux 5.17 undefined
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 430.21 MB / 15.62 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.9.1/bin/yarn
    npm: 7.24.2 - ~/.nvm/versions/node/v16.9.1/bin/npm
  Browsers:
    Brave Browser: 101.1.38.111
    Chromium: 101.0.4951.54
    Firefox: 100.0
  npmPackages:
    @sveltejs/vite-plugin-svelte: ^1.0.0-next.44 => 1.0.0-next.44 
    svelte: ^3.48.0 => 3.48.0 
    vite: ^2.9.9 => 2.9.9
```

### Severity

annoyance

**Comment by dominikg** [comment] 2022-05-24 21:58
generate is indeed hardcoded: https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/vite-plugin-svelte/src/utils/compile.ts#L24

If you don't want an ssr build and instead render the result yourself with jsdom, not passing `--ssr` to vite build could work: 
`"build:server": "vite build --outDir dist/server src/main.js"`

**Comment by bluwy** [comment] 2022-05-25 14:55
I don't think we should allow users to override `generate`. If the build is compiling for SSR, we should generate for SSR, otherwise it opens up a footgun for the users to break their builds. Similarly that `format` is always `esm` because the build needs ESM.

I think the workaround is the way to go for now for this special case, otherwise @dominikg had also suggested using `experimental.dynamicCompilerOptions` to force it to `generate: 'dom'` (the options aren't validated thereafter).

**Comment by jakobrosenberg** [comment] 2022-05-26 06:16
I don't see the footgun. It's a very specific option that nobody accidentally types. If you do add it, it does exactly what it's documented to do. It's self-explanatory. Vite has 100s of options, which, if used incorrectly, could break a build.

Pros of fixing this
- predictability - options do what they say.
- broader scope of use cases - eg.: faster app tests, simpler SSR and isomorphic client / server code.
- enforces correct configs.
- if you try to fix an unrelated issue with `generate: 'dom'`, you will instantly know that it doesn't work.

Cons
- if you break your config, you break your build (this is a pro)

It's your choice, but I would favor [explicitness, transparency and predictability](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) any day of the week. Arbitrarily changing the behavior of documented options only leads to confusion and unnecessary hacks.

At any rate, thanks for maintaining this. ❤️

**Comment by bluwy** [comment] 2022-05-26 08:55
It is [documented](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#compileroptions) that `generate` is non-configurable. To be honest, I don't quite agree with the pros listed but it may be a matter of perspective, if you call `vite build --ssr` and expect a non-ssr output because of `generate: 'dom'`, it conflicts with the intention of the command.

I'm still leaning to not fixing this. Dominik has discussed with me too of how this usecase was needed, and I understand how this is unexpected from your end, but I think it's an edge case that the workaround is the solution for now.

**Comment by Conduitry** [comment] 2022-05-26 11:22
Maybe this plugin can throw if you've passed in one of the non-configurable options, rather than silently ignoring them?

**Comment by dominikg** [comment] 2022-05-26 20:29
vite-plugin-svelte@1.0.0-next.45 has been released and includes a warning when users add essential compilerOptions to their config.

dynamicCompilerOptions can be used as an escape hatch at your own risk. Closing this as it is documented - and now warned behavior. not a bug

**Closed by dominikg** 2022-05-26 20:29 UTC
Labels: bug, has-workaround, edge-case

**Comment by jakobrosenberg** [comment] 2022-05-27 07:02
@bluwy is there a specific entry in the pros list you don't agree with?

As for SSR. SSR simply means prerendering HTML on the server. There's nothing edge or "non-ssr" about using a DOM bundle for that. In fact DOM bundles have been used for SSR for about a decade now.  

Thanks for pointing out `experimental.dynamicCompilerOptions`. I'll give that a try. 🙂
