### ISSUE TITLE
Inspector: Space separated folder names crashed the process

### ISSUE THREAD

**Issue by hAbuMustafa** [sveltejs/vite-plugin-svelte#752] opened 2023-09-17 09:58 UTC
### Describe the bug

When I use the inspector to open a component in the code editor, I get the following error:
```shell
'C:\Users\Mohamed' is not recognized as an internal or external command,
operable program or batch file.

Could not open Modal.svelte in the editor.
The editor process exited with an error: (code 1).
```

The user folder name is actually "Mohamed Hosam" which contains a space in it, and, I assume it is the space that is causing the process to crash.

Of course, I would have changed the folder name if it wasn't the Windows username on my work laptop, so, unfortunately, it's not an option in my case.

### Reproduction

1. Create a project inside a folder that has 'space' in the pathname.
2. Add inspector to `svelte.config.js`.
3. Run Dev server.
4. `meta-shift` and Click on any component.
5. Check the server console.

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 1020.08 MB / 7.84 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 116.0.5845.188
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.69)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.5.0 => 1.25.0
    svelte: ^3.54.0 => 3.59.2
    vite: ^4.3.0 => 4.4.9
```

**Comment by dominikg** [comment] 2023-09-17 10:11
duplicate of https://github.com/sveltejs/vite-plugin-svelte/issues/608  see comments there for a workaround.

**Closed by dominikg** 2023-09-17 10:11 UTC
Labels: bug, triage
