### ISSUE TITLE
Error: failed to transform tagged svelte request

### ISSUE THREAD

**Issue by probablykasper** [sveltejs/vite-plugin-svelte#118] opened 2021-07-24 22:52 UTC
### Describe the bug

After upgrading from `1.0.0-next.11` I'm getting errors saying `failed to transform tagged svelte request` and `Internal server error: failed to transform tagged svelte request for id src/Counter.svelte?svelte&type=style&lang.css`.

### Reproduction

1. `git clone https://github.com/probablykasper/vite-plugin-svelte-transform-bug`
2. `npm i`
3. Run `npm run dev` and open the website

### Logs

```shell
vite-plugin-svelte-transform-bug ❱ npm run dev

> @ dev /Users/kasper/dev/git/vite-plugin-svelte-transform-bug
> vite


  vite v2.3.8 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 202ms.

12:46:45 AM [vite-plugin-svelte] failed to transform tagged svelte request
{
  id: 'src/App.svelte?svelte&type=style&lang.css',
  filename: 'src/App.svelte',
  normalizedFilename: '/App.svelte',
  cssId: 'src/App.svelte?svelte&type=style&lang.css',
  query: { svelte: true, type: 'style', 'lang.css': true },
  timestamp: 1627166805573,
  ssr: false
}
12:46:45 AM [vite] Internal server error: failed to transform tagged svelte request for id src/App.svelte?svelte&type=style&lang.css
  Plugin: vite-plugin-svelte
  File: src/App.svelte?svelte&type=style&lang.css
      at TransformContext.transform (/Users/kasper/dev/git/vite-plugin-svelte-transform-bug/node_modules/@sveltejs/vite-plugin-svelte/dist/index.cjs:1128:15)
      at Object.transform (/Users/kasper/dev/git/vite-plugin-svelte-transform-bug/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:44796:53)
      at transformRequest (/Users/kasper/dev/git/vite-plugin-svelte-transform-bug/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:60267:51)
      at async viteTransformMiddleware (/Users/kasper/dev/git/vite-plugin-svelte-transform-bug/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:60405:32)
12:46:45 AM [vite-plugin-svelte] failed to transform tagged svelte request
{
  id: 'src/Counter.svelte?svelte&type=style&lang.css',
  filename: 'src/Counter.svelte',
  normalizedFilename: '/Counter.svelte',
  cssId: 'src/Counter.svelte?svelte&type=style&lang.css',
  query: { svelte: true, type: 'style', 'lang.css': true },
  timestamp: 1627166805593,
  ssr: false
}
12:46:45 AM [vite] Internal server error: failed to transform tagged svelte request for id src/Counter.svelte?svelte&type=style&lang.css
  Plugin: vite-plugin-svelte
  File: src/Counter.svelte?svelte&type=style&lang.css
      at TransformContext.transform (/Users/kasper/dev/git/vite-plugin-svelte-transform-bug/node_modules/@sveltejs/vite-plugin-svelte/dist/index.cjs:1128:15)
      at Object.transform (/Users/kasper/dev/git/vite-plugin-svelte-transform-bug/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:44796:53)
      at transformRequest (/Users/kasper/dev/git/vite-plugin-svelte-transform-bug/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:60267:51)
      at async viteTransformMiddleware (/Users/kasper/dev/git/vite-plugin-svelte-transform-bug/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:60405:32)
```

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 74.47 MB / 32.00 GB
    Shell: 3.2.2 - /usr/local/bin/fish
  Binaries:
    Node: 14.16.0 - /var/folders/44/3sxbyc2d6wg90mj1s7s59bnm0000gn/T/fnm_multishells/34346_1627165620684/bin/node
    Yarn: 1.22.10 - /var/folders/44/3sxbyc2d6wg90mj1s7s59bnm0000gn/T/fnm_multishells/34346_1627165620684/bin/yarn
    npm: 6.14.11 - /var/folders/44/3sxbyc2d6wg90mj1s7s59bnm0000gn/T/fnm_multishells/34346_1627165620684/bin/npm
  Browsers:
    Brave Browser: 91.1.26.77
    Chrome: 91.0.4472.164
    Firefox: 89.0.2
    Safari: 14.1.2
  npmPackages:
    vite: ^2.3.8 => 2.4.3
```

### Severity

blocking all usage of vite-plugin-svelte

**Comment by dominikg** [comment] 2021-07-24 23:02
duplicate of https://github.com/sveltejs/vite-plugin-svelte/issues/113

**Closed by dominikg** 2021-07-24 23:02 UTC
Labels: bug, triage
