### ISSUE TITLE
4.0-next: Unterminated JSX contentssvelte(js_parse_error)

### ISSUE THREAD

**Issue by niemyjski** [sveltejs/vite-plugin-svelte#981] opened 2024-09-11 13:33 UTC
### Describe the bug

Getting Unterminated JSX contents after upgrading to 4.0 preview.

```
 let sortedHeaders = $derived(
        Object.keys(request.headers || {})
            .sort()
            .reduce(
                (acc, key) => {
                    acc[key] = request.headers?.[key].join(',') ?? '';
                    return acc;
                },
                <Record<string, string>>{}
            )
    );
```

![image](https://github.com/user-attachments/assets/efae3b78-438c-4b45-b6d7-5af43a0928e7)

### Reproduction URL

https://github.com/exceptionless/Exceptionless/tree/main/src/Exceptionless.Web/ClientApp

### Reproduction

Build the project

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 8.38 GB / 31.91 GB
  Binaries:
    Node: 22.8.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.3 - ~\AppData\Roaming\npm\npm.CMD
    pnpm: 9.9.0 - C:\ProgramData\chocolatey\bin\pnpm.EXE
  Browsers:
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @sveltejs/adapter-static: ^3.0.4 => 3.0.4
    @sveltejs/kit: ^2.5.26 => 2.5.26
    @sveltejs/vite-plugin-svelte: ^4.0.0-next.7 => 4.0.0-next.7
    svelte: ^5.0.0-next.244 => 5.0.0-next.244
    vite: ^5.4.4 => 5.4.4
```

**Comment by Conduitry** [comment] 2024-09-11 13:42
Duplicate of https://github.com/sveltejs/svelte/issues/13179

**Closed by Conduitry** 2024-09-11 13:42 UTC
Labels: bug, triage
