### ISSUE TITLE
Handle `<style global>` in dev 

### ISSUE THREAD

**Issue by kevinflint** [sveltejs/vite-plugin-svelte#834] opened 2024-01-10 18:10 UTC
### Describe the problem

Related to: https://github.com/sveltejs/vite-plugin-svelte/issues/153

For `<style>` blocks `vitePreprocess` prepends/append a `* {}` causing a `.hash {}` to be generated.
AFAIK, there are good reasons for this (see related issue).

> @dominikg
>
> This extra * {} is used to ensure that the svelte compiler adds the components css-hash class to every element of the rendered template. Which in turn means we can get more "css-only" updates when editing classes in template and style sections of a component.

However when a block has styles that must be global, but are tightly coupled to the component, it is frustrating.

### Describe the proposed solution

Ideally, `vitePreprocess` should support the `<style global>` pattern and for `<style global>` blocks it should not emit a `* {}` to cause a hash class to be generated for the component.

### Alternatives considered

Documentation would suggest that instead these styles should be moved into a separate `.css` file (e.g. `+page.css` or `Component.css`).

However this alternative is undesirable when the styles are tightly scoped to a specific `.svelte` component, but need to be global for practical reasons, e.g. 
 - DOM not visible to svelte, because it's generated outside of svelte
 - Using 3rd-party library components that doesn't support modified style
 - etc

### Importance

nice to have

**Comment by dominikg** [comment] 2024-01-10 19:34
`<style global>` is a feature of svelte-preprocess https://github.com/sveltejs/svelte-preprocess?tab=readme-ov-file#global-attribute 

iirc it just wraps the content in a `:global` .  But if you want to target unknown children, it should always happen with a scope selector, or the styles can "bleed out". 

so this should really lead to a warning at least. we may be able to test for the global attribute but i have reservations against it as it could be misunderstood as blessing a feature thats problematic and has more idiomatic alternatives available in vite

**Comment by dominikg** [comment] 2024-01-11 14:47
Also the `* {}` rule is not added by vitePreprocess, but vite-plugin-svelte itself - only during dev. 

If you need support for `<style global>`, you have to use svelte-preprocess instead of vitePreprocess.

It would still add the scope class during dev to improve DX with css updates. 
Are these dev-only scope classes an issue for you @kevinflint ? if yes please clarify why. The only rule they would have if there is no scoped style is `* {}`, so they won't affect the output visually at all.

**Comment by kevinflint** [comment] 2024-01-11 22:51
I must be partially confused somehow.

In one of my use cases, I have a nested component I'm passing a class to as part of a 3rd-party library.

When using `<style> :global(.scoped--nested-class) { ... } </style>`, either the preprocess or the plugin is logging a warning and adding the `hashClass` to the component in __production__ builds.

Switching to using `<style global>` with `svelte-preprocess` is my currently implemented solution, but it seems temporary as the functionality of the two pre-processers may drift apart. 

I'd suggest that I appreciate the original warning, but that guard rails should generally have an escape hatch.

**Comment by dominikg** [comment] 2024-01-12 10:29
if the rule is injected into builds that would be a bug. please file a separate issue and provide a reproduction. It seems unlikely though because like I said, the preprocessor is not used during build:  https://github.com/sveltejs/vite-plugin-svelte/blob/d5a6dad8da2da3e505433e1290e9f2aa9bb82d4e/packages/vite-plugin-svelte/src/utils/compile.js#L84

**Comment by dominikg** [comment] 2024-01-13 10:08
closing this as we do not plan to add `<style global>` support to vitePreprocess. 

Additionally if you insist on using it, you can use onwarn to suppress messages with code `vite-plugin-svelte-css-no-scopable-elements`. 

This only affects `vite dev`, during `vite build` vite-plugin-svelte does not inject anything into your styles or scripts (during dev, scripts get changed to add svelte-hmr).

**Closed by dominikg** 2024-01-13 10:08 UTC
Labels: enhancement, triage

**Comment by kevinflint** [comment] 2024-01-17 16:18
Thanks for calling out the ability to use `onwarn` 🙂

**Comment by Keavon** [comment] 2026-04-04 07:18
It's too bad this is not supported in `vite-plugin-svelte` like it has been in `svelte-preprocess`. But since I was looking to upgrade from the latter to this, I found a decent workaround using a ~10-line function as a Vite plugin to do the `:global { ... }` wrapping automatically. [Here it is](https://github.com/GraphiteEditor/Graphite/blob/e0212ca4b94b1ef392e9e20b629fab47ca039adc/frontend/vite.config.ts#L25-L36), in case it helps someone else.
