### ISSUE TITLE
npm run build retrieves `The argument 'filename' must be a file URL object, file URL string, or absolute path string`

### ISSUE THREAD

**Issue by silvestrevivo** [sveltejs/vite-plugin-svelte#283] opened 2022-02-27 22:42 UTC
### Describe the bug

I've created a npm package that in development it works OK but when I run `npm run build` it retrieves the next error. 

```
[vite-plugin-svelte] The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received '\x00__vite-browser-external?commonjs-proxy'
> The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received '\x00__vite-browser-external?commonjs-proxy'
```

### Reproduction

This is the repo where this is happening. 

https://github.com/silvestrevivo/solana-svelte-counter

I think it would be difficult to reproduce since you need to deploy the smart contract to run the project. **With the SvelteKit version `251` this bug doesn't occur.** As soon as you upgrade SvelteKit, the error happens.  

### Logs

```shell
[vite-plugin-svelte] The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received '\x00__vite-browser-external?commonjs-proxy'
> The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received '\x00__vite-browser-external?commonjs-proxy'
    at new NodeError (node:internal/errors:371:5)
    at createRequire (node:internal/modules/cjs/loader:1210:13)
    at resolveViaPackageJsonSvelte (file:///Users/silvestrevivo/werk/2021/solana/solana-svelte-counter/app/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1427:26)
    at Object.resolveId (file:///Users/silvestrevivo/werk/2021/solana/solana-svelte-counter/app/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1585:24)
    at /Users/silvestrevivo/werk/2021/solana/solana-svelte-counter/app/node_modules/rollup/dist/shared/rollup.js:22795:37
```

### System Info

```shell
.
```

### Severity

annoyance

**Comment by ashwinvasudevan** [comment] 2022-02-28 07:02
try, catch has been removed around `resolveViaPackageJsonSvelte` fn. Adding try catch seems to solve the error. Downgrade to `@sveltejs/vite-plugin-svelte@1.0.0-next.37` to solve the issue for now

**Comment by silvestrevivo** [comment] 2022-02-28 07:48
@ashwinvasudevan thanks for the answer. I had to downgrade to `@sveltejs/vite-plugin-svelte@1.0.0-next.36` because sveltekit over `251` is overwriting to `@sveltejs/vite-plugin-svelte@1.0.0-next.38`. But you are right, it seems an issue from that version what is causing the error. 

I get this problem with this package I am working on right now https://www.npmjs.com/package/@svelte-on-solana/wallet-adapter-ui that is the Official Wallet adapter for Solana Dapps. This is blocking me right now to make support to Svelte devs who want to develop Web3 based on Solana. 

I hope this can be solved soon. Thanks!!!!

**Comment by bluwy** [comment] 2022-03-02 03:19
#286 is released in 1.0.0-next.38 which fixes this. Please upgrade to that version to resolve this issue.

**Comment by nikkwong** [comment] 2022-03-02 03:26
Like so? I am still getting the same issue: 
![Screen Shot 2022-03-01 at 7 26 11 PM](https://user-images.githubusercontent.com/8837416/156289314-3d9e90a9-8dad-4c0a-b142-482d0511e238.png)
)

**Comment by bluwy** [comment] 2022-03-02 03:29
If the workaround proposed in this issue didn't work for you, then it probably means you're hitting a slightly different issue then. I'd suggest providing repros and logs, or create a new issue with it so we can debug further.

**Comment by nikkwong** [comment] 2022-03-02 03:39
Thanks! It certainly seems to be the same issue, since the logging output is the same as the originally referenced one:

```
[vite-plugin-svelte] The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received '\x00__vite-browser-external?commonjs-proxy'
> The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received '\x00__vite-browser-external?commonjs-proxy'
    at new NodeError (internal/errors.js:322:7)
    at createRequire (internal/modules/cjs/loader.js:1182:13)
    at resolveViaPackageJsonSvelte (file:///node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.38_svelte@3.30.1+vite@2.8.4/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1427:26)
```

**Comment by xpluscal** [comment] 2022-03-02 05:25
Actually reverting: It is caused by vite-plugin-svelte apparently. the plugin was installed as dep of kit

**Comment by bluwy** [comment] 2022-03-02 05:38
Ugh I'm sorry. Turns out the fix is not released yet 😢

**Comment by xpluscal** [comment] 2022-03-02 05:40
thx @bluwy. Any known workarounds?

I'm curious how that happens even if no minor / major version bumps of svelte/kit or /vite-plugin-svelte happened?
Any versions that would not encounter this issue?
As @nikkwong mentioned it is breaking build processes (for us as well)

**Comment by bluwy** [comment] 2022-03-02 05:42
Might be an upgrade to Vite that causes the issue. But usually it's hard to know where this was caused on this part of the code. I'll check with @dominikg to make a new release soon.

**Comment by xpluscal** [comment] 2022-03-02 05:43
super thank you @bluwy 🙏

**Closed** 2022-03-02 06:55 UTC
Labels: bug

**Comment by silvestrevivo** [comment] 2022-03-02 07:54
@dominikg @bluwy thank you so much for solving this!!!

**Comment by Nisthar** [comment] 2022-05-16 07:12
> @dominikg @bluwy thank you so much for solving this!!!

I am getting the same error still 

![image](https://user-images.githubusercontent.com/11994157/168538378-988bbc41-512f-44ca-aef2-88532f55a27c.png)

**Comment by dominikg** [comment] 2022-05-16 08:05
@Nisthar 

this seems to be a different cause with a similar error message. Please file a new issue and provide a reproduction.

**Comment by Nisthar** [comment] 2022-05-16 09:13
> @Nisthar
> 
> this seems to be a different cause with a similar error message. Please file a new issue and provide a reproduction.
ok created a new issue here https://github.com/sveltejs/vite-plugin-svelte/issues/340
