### ISSUE TITLE
Inspector — Clicking on a component does not open the corresponding file in the editor on Windows + WSL2 setup

### ISSUE THREAD

**Issue by codepainting** [sveltejs/vite-plugin-svelte#481] opened 2022-11-01 20:44 UTC
### Describe the bug

On a Windows + WSL2 setup, the wonderful inspector feature only works partially.
— Highlighting elements works perfectly and components are being recognized correctly.
— But: Clicking on a component does not open the corresponding file in the editor.

The following error messages are being displayed in the terminal:
`Could not open +page.svelte in the editor. `
`Could not open Buttonk.svelte in the editor.`
which means, that thy are correctly recognized, but not opened.

Adding an .env file with LAUNCH_EDITOR=code variable does not solve the problem.

The issue might or might not be related to the launch-editor, so I mentioned it also over at:
https://github.com/yyx990803/launch-editor/issues/16#issuecomment-1298304203

### Reproduction URL

new SvelteKit demo app

### Reproduction

1) Run this on a Windows + WSL2 + VSCode setup.
2) Create new SvelteKit app.
3) Enable inspector by adding to svelte.config.js:
```
vitePlugin: {
	experimental: {
		inspector: {
			toggleKeyCombo: 'control-shift',
			holdMode: true,
			showToggleButton: 'always',
			toggleButtonPos: 'top-right',
		}
	},
}
```
4) Run dev server and select some components.
5) See how the aforementioned errors are being logged to the terminal.

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
    Memory: 23.05 GB / 25.02 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.volta/tools/image/node/16.18.0/bin/node
    Yarn: 1.22.4 - ~/.volta/bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/node/16.18.0/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.86 
    @sveltejs/kit: next => 1.0.0-next.531 
    svelte: ^3.46.0 => 3.52.0 
    vite: ^3.1.0 => 3.2.2
```

**Comment by Conduitry** [comment] 2022-11-01 20:49
Duplicate of #355. As indicated in that issue, the way to fix this would be upstream in launch-editor, in the issue you linked to.

**Closed by Conduitry** 2022-11-01 20:49 UTC
Labels: bug, triage
