### ISSUE TITLE
@sveltejs/kit and vite@3 crash Chrome

### ISSUE THREAD

**Issue by sserdyuk** [sveltejs/vite-plugin-svelte#409] opened 2022-08-08 16:18 UTC
### Describe the bug

We've noticed that a certain page causes Chrome to hang or crash. I was able to create a sample project for this issue. I think it's likely something to do with Vite in dev mode. If I build the project and preview it, everything is working fine.

We've currently switched to Firefox as a workaround. 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/395998/183464413-5dcbd8b2-47f5-45b3-a2a4-36f9b88be1e4.gif)

### Reproduction

Please clone https://github.com/sserdyuk/vitebug-08-08-2022

Please run `npm run dev` and navigate to `http://localhost:4100/mock3/explore`. The page usually renders once but crashes Chrome on a refresh. I am also noticing it takes quite a bit of time to load that page in the first place.

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 21.54 GB / 30.74 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.14.0 - ~/.bin/node/bin/node
    npm: 8.3.1 - ~/.bin/node/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 103.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/adapter-node: ^1.0.0-next.71 => 1.0.0-next.86 
    @sveltejs/kit: next => 1.0.0-next.405 
    @sveltejs/vite-plugin-svelte: ^1.0.0-next.36 => 1.0.1 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.4
```

### Severity

serious, but I can work around it

**Comment by dominikg** [comment] 2022-08-09 06:50
to work around this problem, prefer deep imports of .svelte files, see also https://github.com/rgossiaux/svelte-headlessui/issues/107

I wonder if the addition of tailwind in the reproduction plays a part here too.

**Comment by bluwy** [comment] 2022-08-25 16:15
Another report on [discord](https://discord.com/channels/804011606160703521/1012085571985866914/1012393253137547324) showed that `@svelteuidev/core` has a similar issue, where we did prebundle the svelte library, but Vite doesn't resolve to the prebundled file.

**Comment by benmccann** [comment] 2022-08-29 18:12
I found the issue with `@rgossiaux/svelte-headlessui`. The bug was in the reproduction. It had `type="ts"`, which as far as I know is not valid. If you change it to `lang="ts"` then it works:

https://github.com/sserdyuk/vitebug-08-08-2022/blob/d6a649d6bc535734347c30a6ac3b6c6d7c9ff1cf/src/routes/mock3/_shared/Explore.svelte#L1

**Comment by benmccann** [comment] 2022-08-29 18:18
I think we can close this issue now. I've filed a new one to track the `@svelteuidev/core` issue: https://github.com/sveltejs/vite-plugin-svelte/issues/421

**Comment by dominikg** [comment] 2022-08-29 20:49
closing per @benmccann's comment.

The crash in the original report likely happened due to the large number of requests.

**Closed by dominikg** 2022-08-29 20:49 UTC
