### ISSUE TITLE
Full HMR support for CSS classes

### ISSUE THREAD

**Issue by garlandcrow** [sveltejs/vite-plugin-svelte#86] opened 2021-07-09 01:38 UTC
### Describe the problem

I am not 100% sure if this is a bug or a feature request. I was going to give vite a go and test out the HMR support, and it seems to only work for style changes that are in the `<style>` section and not for when you change css classes on an html element. In the template setup I get from `npm init @vitejs/app test_create_vite --template svelte`, if I add a wrapper div around the button text like this: 

```html
<button on:click={increment}>
  <div class="bg-green">
    Clicks: {count}
  </div>
</button>
```
and add this to the `<style>` section:
```css
  .bg-blue {
    background-color: blue;
  }
  .bg-green {
    background-color: green;
  }
```
Click the button a few times then changing the css class from `bg-green` to `bg-blue` will reset the counter and apply the new styles. Maybe this is a known limitation or something with how svelte processing things that makes the HMR not possible? If so, is there any link to where I can follow progress on this?

### Describe the proposed solution

Just that HMR would apply to the HTML element changes as well.

### Alternatives considered

Never use CSS classes (sorry tailwind) on HTML element and always do styling in the `<style>` section.

### Importance

would make my life easier

**Comment by bluwy** [comment] 2021-07-09 07:08
This is likely an issue for https://github.com/rixo/svelte-hmr, but to add, this seems to happen when you edit anything in the markup, not just limited to the `class`. I believe this is related to `preserveLocalState` too, which you can turn it on in the plugin options `hot.preserveLocalState` or with `// @hmr:keep`, but it isn't recommended due to [unpredictable behaviours](https://github.com/rixo/svelte-hmr#preservelocalstate).

**Comment by dominikg** [comment] 2021-07-09 08:56
The way svelte components are compiled requires it to update the js module when template parts change, no way around that. 
Like bluwy suggested you can use special comments to preserve internal state across updates, proceed with caution.

For the style section, vite-plugin-svelte uses a virtual css module that can be updated separately. To benefit from that, make sure your style node is last (recommended ordering by prettier-plugin-svelte ) and use css selectors to target parts of your component.

```svelte
<div class="my-bg">some div</div>
<style>
  .my-bg {
    background-color: blue; /* editing here only updates css module */
  }
</style>
```

you can even use tailwinds @apply in the style block.

Closing here as it works as designed and hmr itself works. It's just internal component state that is reset on js update.

**Closed by dominikg** 2021-07-09 08:56 UTC
Labels: enhancement, triage

**Comment by garlandcrow** [comment] 2021-07-09 10:57
@dominikg I can do a PR for some documentation change to make it clearer around HMR expectations. Any opinion about where that is best to be places? (maybe not on this repo?) Because I couldn't find anywhere saying what the expectations should be for HMR.
